/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.dodgybits.android.shuffle;

public final class R {
    public static final class anim {
        public static final int fade=0x7f040000;
        public static final int layout_grid_fade=0x7f040001;
    }
    public static final class array {
        public static final int background_colours=0x7f050006;
        public static final int clean=0x7f050000;
        public static final int help_screens=0x7f050003;
        public static final int perspectives=0x7f050001;
        public static final int preference_screens=0x7f050004;
        public static final int text_colours=0x7f050005;
        public static final int view_types=0x7f050002;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int applications_accessories=0x7f020000;
        public static final int applications_development=0x7f020001;
        public static final int applications_games=0x7f020002;
        public static final int applications_graphics=0x7f020003;
        public static final int applications_internet=0x7f020004;
        public static final int applications_office=0x7f020005;
        public static final int appointment_new=0x7f020006;
        public static final int arrow_right_float=0x7f020007;
        public static final int box=0x7f020008;
        public static final int computer=0x7f020009;
        public static final int date_blue=0x7f02002c;
        public static final int dialog_error=0x7f02000a;
        public static final int dialog_information=0x7f02000b;
        public static final int dialog_warning=0x7f02000c;
        public static final int document_new=0x7f02000d;
        public static final int document_open=0x7f02000e;
        public static final int edit_clear=0x7f02000f;
        public static final int edit_delete=0x7f020010;
        public static final int edit_find_replace=0x7f020011;
        public static final int edit_undo=0x7f020012;
        public static final int emblem_favorite=0x7f020013;
        public static final int emblem_important=0x7f020014;
        public static final int even_stripe=0x7f02002a;
        public static final int folder_new=0x7f020015;
        public static final int format_justify_fill=0x7f020016;
        public static final int go_down=0x7f020017;
        public static final int go_home=0x7f020018;
        public static final int go_up=0x7f020019;
        public static final int green=0x7f02002f;
        public static final int help_browser=0x7f02001a;
        public static final int icon=0x7f02001b;
        public static final int light_blue=0x7f02002d;
        public static final int light_yellow=0x7f02002e;
        public static final int list_add=0x7f02001c;
        public static final int list_remove=0x7f02001d;
        public static final int mail_attachment=0x7f02001e;
        public static final int network_wireless=0x7f02001f;
        public static final int odd_stripe=0x7f02002b;
        public static final int office_calendar=0x7f020020;
        public static final int preferences_desktop=0x7f020021;
        public static final int preferences_system=0x7f020022;
        public static final int preferences_system_windows=0x7f020023;
        public static final int process_stop=0x7f020024;
        public static final int system_file_manager=0x7f020025;
        public static final int system_users=0x7f020026;
        public static final int transparent_blue=0x7f020030;
        public static final int utilities_terminal=0x7f020027;
        public static final int video_x_generic=0x7f020028;
        public static final int x_office_address_book=0x7f020029;
    }
    public static final class id {
        public static final int appearance_table=0x7f080019;
        public static final int cancel_button=0x7f08000c;
        public static final int clean_slate_button=0x7f080021;
        public static final int colourGrid=0x7f080003;
        public static final int colour_change_button=0x7f080006;
        public static final int colour_display=0x7f080005;
        public static final int completed=0x7f08002e;
        public static final int completed_checkbox=0x7f08002a;
        public static final int contact=0x7f08002c;
        public static final int context=0x7f080014;
        public static final int contextDisplay=0x7f080013;
        public static final int context_icon=0x7f08002d;
        public static final int context_view=0x7f080023;
        public static final int day_button=0x7f080000;
        public static final int default_context=0x7f080024;
        public static final int delete_completed=0x7f08001f;
        public static final int delete_completed_button=0x7f080020;
        public static final int description=0x7f080015;
        public static final int details=0x7f080017;
        public static final int display_context=0x7f08001a;
        public static final int display_details=0x7f08001e;
        public static final int display_due_date=0x7f08001b;
        public static final int display_icon=0x7f08001c;
        public static final int display_project=0x7f08001d;
        public static final int due_date=0x7f080018;
        public static final int due_date_clear_button=0x7f080029;
        public static final int due_date_display=0x7f080027;
        public static final int due_date_set_button=0x7f080028;
        public static final int edit_button=0x7f08002f;
        public static final int extras=0x7f08002b;
        public static final int help_screen=0x7f08000e;
        public static final int help_shortcuts=0x7f080010;
        public static final int help_text=0x7f08000f;
        public static final int icon=0x7f08000d;
        public static final int iconGrid=0x7f080011;
        public static final int icon_clear_button=0x7f08000b;
        public static final int icon_display=0x7f080007;
        public static final int icon_none=0x7f080008;
        public static final int icon_set_button=0x7f080009;
        public static final int main=0x7f080026;
        public static final int month_button=0x7f080002;
        public static final int name=0x7f080004;
        public static final int project=0x7f080016;
        public static final int project_view=0x7f080022;
        public static final int relLayout=0x7f080012;
        public static final int sample_data_button=0x7f080030;
        public static final int save_button=0x7f08000a;
        public static final int task_list=0x7f080025;
        public static final int week_button=0x7f080001;
    }
    public static final class layout {
        public static final int calendar=0x7f030000;
        public static final int colour_picker=0x7f030001;
        public static final int context_editor=0x7f030002;
        public static final int context_view=0x7f030003;
        public static final int contexts=0x7f030004;
        public static final int expandable_context_view=0x7f030005;
        public static final int expandable_contexts=0x7f030006;
        public static final int expandable_project_view=0x7f030007;
        public static final int expandable_projects=0x7f030008;
        public static final int help=0x7f030009;
        public static final int icon_picker=0x7f03000a;
        public static final int list_item_view=0x7f03000b;
        public static final int list_task_view=0x7f03000c;
        public static final int preferences_appearance=0x7f03000d;
        public static final int preferences_clean=0x7f03000e;
        public static final int preferences_layout=0x7f03000f;
        public static final int project_editor=0x7f030010;
        public static final int projects=0x7f030011;
        public static final int tabbed_due_tasks=0x7f030012;
        public static final int task_editor=0x7f030013;
        public static final int task_list=0x7f030014;
        public static final int task_view=0x7f030015;
        public static final int welcome=0x7f030016;
    }
    public static final class string {
        /**   Activity titles 
         */
        public static final int app_name=0x7f060000;
        public static final int archived_title=0x7f06003c;
        public static final int cancel_button_title=0x7f06002b;
        public static final int clean_inbox_button_title=0x7f06004a;
        public static final int clean_inbox_message=0x7f060052;
        public static final int clean_slate_button_title=0x7f06004b;
        public static final int clean_slate_message=0x7f060053;
        public static final int clean_slate_title=0x7f060036;
        public static final int clean_task_message=0x7f060051;
        public static final int clear_button_title=0x7f060026;
        /**   project & context edit screens 
         */
        public static final int colour_title=0x7f06003b;
        public static final int completed_title=0x7f06003a;
        public static final int contact_title=0x7f060023;
        public static final int context_icon_title=0x7f060044;
        public static final int context_name=0x7f060030;
        public static final int context_name_title=0x7f060045;
        public static final int context_title=0x7f060022;
        public static final int context_view_title=0x7f060047;
        /**   Calendar screen 
         */
        public static final int day_button_title=0x7f060040;
        public static final int default_context_title=0x7f06003f;
        public static final int delete_completed_button_title=0x7f060049;
        public static final int delete_completed_title=0x7f060048;
        public static final int delete_warning=0x7f060050;
        public static final int description_title=0x7f060038;
        public static final int details_title=0x7f060024;
        /**   preferences screen 
         */
        public static final int display_task_list_title=0x7f060043;
        public static final int done_button_title=0x7f06002a;
        public static final int due_date_title=0x7f060039;
        public static final int edit_button_title=0x7f060027;
        public static final int error_message=0x7f060055;
        public static final int error_title=0x7f060054;
        public static final int extras_button_title=0x7f060028;
        public static final int help0=0x7f060059;
        public static final int help1=0x7f06005a;
        public static final int help2=0x7f06005b;
        public static final int help3=0x7f06005c;
        public static final int help4=0x7f06005d;
        public static final int help5=0x7f06005e;
        public static final int help6=0x7f06005f;
        public static final int help7=0x7f060060;
        public static final int help8=0x7f060061;
        public static final int icon_title=0x7f06003d;
        public static final int info_title=0x7f06002d;
        /**   task edit screen 
         */
        public static final int initial_text=0x7f060037;
        public static final int menu_complete=0x7f060018;
        /**   Option menu 
         */
        public static final int menu_delete=0x7f060017;
        public static final int menu_discard=0x7f06001d;
        public static final int menu_help=0x7f060020;
        public static final int menu_insert=0x7f06001b;
        public static final int menu_move_down=0x7f06001a;
        public static final int menu_move_up=0x7f060019;
        public static final int menu_preferences=0x7f06001f;
        public static final int menu_revert=0x7f06001c;
        public static final int menu_view=0x7f06001e;
        public static final int month_button_title=0x7f060042;
        public static final int name_title=0x7f06003e;
        public static final int no_contexts=0x7f06004f;
        public static final int no_due_tasks=0x7f06004d;
        public static final int no_projects=0x7f06004e;
        /**   messages 
         */
        public static final int no_tasks=0x7f06004c;
        public static final int nothing=0x7f060031;
        public static final int project_name=0x7f06002f;
        /**   general purpose 
         */
        public static final int project_title=0x7f060021;
        public static final int project_view_title=0x7f060046;
        /**   Welcome screen 
         */
        public static final int sample_data_title=0x7f060035;
        public static final int save_button_title=0x7f060029;
        public static final int set_button_title=0x7f060025;
        public static final int task_name=0x7f06002e;
        public static final int title_calendar=0x7f060014;
        public static final int title_context=0x7f060003;
        public static final int title_context_tasks=0x7f060016;
        public static final int title_due_tasks=0x7f060005;
        public static final int title_edit_context=0x7f06000c;
        public static final int title_edit_project=0x7f06000a;
        public static final int title_edit_task=0x7f060007;
        public static final int title_help=0x7f060012;
        public static final int title_icon_picker=0x7f060013;
        public static final int title_inbox=0x7f060001;
        public static final int title_new_context=0x7f06000b;
        public static final int title_new_project=0x7f060009;
        public static final int title_new_task=0x7f060006;
        public static final int title_next_tasks=0x7f060004;
        public static final int title_preferences=0x7f06000e;
        public static final int title_preferences_appearance=0x7f06000f;
        public static final int title_preferences_clean=0x7f060011;
        public static final int title_preferences_layout=0x7f060010;
        public static final int title_project=0x7f060002;
        public static final int title_project_tasks=0x7f060015;
        public static final int title_task_extras=0x7f06000d;
        public static final int title_view_task=0x7f060008;
        public static final int today=0x7f060033;
        public static final int undefined=0x7f060032;
        public static final int warning_title=0x7f06002c;
        public static final int week_button_title=0x7f060041;
        public static final int welcome1=0x7f060056;
        public static final int welcome2=0x7f060057;
        public static final int welcome3=0x7f060058;
        public static final int yesterday=0x7f060034;
    }
    public static final class style {
        public static final int autocomplete_text=0x7f070006;
        public static final int centered_row=0x7f07000d;
        public static final int context=0x7f070005;
        public static final int detail_label=0x7f070007;
        public static final int due_date=0x7f07000c;
        public static final int editable_text=0x7f070004;
        public static final int image=0x7f070002;
        public static final int label=0x7f070000;
        /**  
    	<item name="android:background">@drawable/light_yellow</item>
        <item name="android:textColor">@drawable/green</item>
         
         */
        public static final int list=0x7f070001;
        public static final int sub_text_1=0x7f070008;
        public static final int sub_text_2=0x7f070009;
        public static final int text=0x7f070003;
        public static final int top_row=0x7f07000e;
        public static final int view_label=0x7f07000b;
        public static final int view_text=0x7f07000a;
    }
}
