/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.dodgybits.android.shuffle;

public final class R {
    public static final class anim {
        public static final int fade=0x7f040000;
        public static final int layout_grid_fade=0x7f040001;
    }
    public static final class array {
        public static final int background_colours=0x7f060007;
        public static final int clean=0x7f060000;
        public static final int clean_keys=0x7f060001;
        public static final int help_screens=0x7f060004;
        public static final int perspectives=0x7f060002;
        public static final int preference_screens=0x7f060005;
        public static final int text_colours=0x7f060006;
        public static final int view_types=0x7f060003;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int applications_accessories=0x7f020000;
        public static final int applications_accessories_small=0x7f020001;
        public static final int applications_development=0x7f020002;
        public static final int applications_development_small=0x7f020003;
        public static final int applications_games=0x7f020004;
        public static final int applications_games_small=0x7f020005;
        public static final int applications_graphics=0x7f020006;
        public static final int applications_graphics_small=0x7f020007;
        public static final int applications_internet=0x7f020008;
        public static final int applications_internet_small=0x7f020009;
        public static final int applications_office=0x7f02000a;
        public static final int applications_office_small=0x7f02000b;
        public static final int appointment_new=0x7f02000c;
        public static final int black=0x7f02004d;
        public static final int box=0x7f02000d;
        public static final int btn_check_on=0x7f02000e;
        public static final int computer=0x7f02000f;
        public static final int computer_small=0x7f020010;
        public static final int dark_blue=0x7f020044;
        public static final int dark_brown=0x7f02004a;
        public static final int dark_gray=0x7f02004c;
        public static final int dark_header=0x7f020011;
        public static final int dark_header_dithered=0x7f020012;
        public static final int dialog_error=0x7f020013;
        public static final int dialog_information=0x7f020014;
        public static final int dialog_warning=0x7f020015;
        public static final int document_new=0x7f020016;
        public static final int document_open=0x7f020017;
        public static final int edit_clear=0x7f020018;
        public static final int edit_delete=0x7f020019;
        public static final int edit_find_replace=0x7f02001a;
        public static final int edit_undo=0x7f02001b;
        public static final int emblem_favorite=0x7f02001c;
        public static final int emblem_favorite_small=0x7f02001d;
        public static final int emblem_important=0x7f02001e;
        public static final int emblem_important_small=0x7f02001f;
        public static final int even_stripe=0x7f02003e;
        public static final int folder_new=0x7f020020;
        public static final int format_justify_fill=0x7f020021;
        public static final int go_down=0x7f020022;
        public static final int go_home=0x7f020023;
        public static final int go_home_small=0x7f020024;
        public static final int go_up=0x7f020025;
        public static final int green=0x7f020046;
        public static final int help_browser=0x7f020026;
        public static final int icon=0x7f020027;
        public static final int light_blue=0x7f020042;
        public static final int light_brown=0x7f02004b;
        public static final int light_gray=0x7f020049;
        public static final int light_yellow=0x7f020045;
        public static final int list_add=0x7f020028;
        public static final int list_remove=0x7f020029;
        public static final int mail_attachment=0x7f02002a;
        public static final int network_wireless=0x7f02002b;
        public static final int network_wireless_small=0x7f02002c;
        public static final int odd_stripe=0x7f02003f;
        public static final int office_calendar=0x7f02002d;
        public static final int office_calendar_small=0x7f02002e;
        public static final int pale_blue=0x7f020043;
        public static final int pale_weak_cyan=0x7f020041;
        public static final int pale_yellow=0x7f020040;
        public static final int preferences_desktop=0x7f02002f;
        public static final int preferences_system=0x7f020030;
        public static final int preferences_system_windows=0x7f020031;
        public static final int process_stop=0x7f020032;
        public static final int system_file_manager=0x7f020033;
        public static final int system_file_manager_small=0x7f020034;
        public static final int system_users=0x7f020035;
        public static final int system_users_small=0x7f020036;
        public static final int transparent_blue=0x7f020047;
        public static final int user_input_icon=0x7f020037;
        public static final int utilities_terminal=0x7f020038;
        public static final int utilities_terminal_small=0x7f020039;
        public static final int video_x_generic=0x7f02003a;
        public static final int video_x_generic_small=0x7f02003b;
        public static final int white=0x7f020048;
        public static final int x_office_address_book=0x7f02003c;
        public static final int x_office_address_book_small=0x7f02003d;
    }
    public static final class id {
        public static final int appearance_layout=0x7f090017;
        public static final int clean_slate_button=0x7f09001f;
        public static final int colourGrid=0x7f090003;
        public static final int colour_change_button=0x7f090006;
        public static final int colour_display=0x7f090005;
        public static final int completed=0x7f090029;
        public static final int completed_checkbox=0x7f090026;
        public static final int context=0x7f090016;
        public static final int contextDisplay=0x7f090027;
        public static final int context_icon=0x7f090028;
        public static final int day_button=0x7f090000;
        public static final int default_context=0x7f090020;
        public static final int delete_completed=0x7f09001d;
        public static final int delete_completed_button=0x7f09001e;
        public static final int description=0x7f090012;
        public static final int details=0x7f090013;
        public static final int display_context=0x7f090018;
        public static final int display_details=0x7f09001c;
        public static final int display_due_date=0x7f090019;
        public static final int display_icon=0x7f09001a;
        public static final int display_project=0x7f09001b;
        public static final int due_date=0x7f090015;
        public static final int due_date_clear_button=0x7f090025;
        public static final int due_date_display=0x7f090023;
        public static final int due_date_set_button=0x7f090024;
        public static final int edit_button=0x7f09002a;
        public static final int help_screen=0x7f09000d;
        public static final int help_shortcuts=0x7f09000f;
        public static final int help_text=0x7f09000e;
        public static final int icon=0x7f09000b;
        public static final int iconGrid=0x7f090010;
        public static final int icon_clear_button=0x7f09000a;
        public static final int icon_display=0x7f090007;
        public static final int icon_none=0x7f090008;
        public static final int icon_set_button=0x7f090009;
        public static final int main=0x7f090022;
        public static final int month_button=0x7f090002;
        public static final int name=0x7f090004;
        public static final int project=0x7f090014;
        public static final int relLayout=0x7f090011;
        public static final int sample_data_button=0x7f09002b;
        public static final int task_list=0x7f090021;
        public static final int text=0x7f09000c;
        public static final int week_button=0x7f090001;
    }
    public static final class layout {
        public static final int calendar=0x7f030000;
        public static final int colour_picker=0x7f030001;
        public static final int context_editor=0x7f030002;
        public static final int context_view=0x7f030003;
        public static final int contexts=0x7f030004;
        public static final int edit_separator=0x7f030005;
        public static final int expandable_context_view=0x7f030006;
        public static final int expandable_contexts=0x7f030007;
        public static final int expandable_project_view=0x7f030008;
        public static final int expandable_projects=0x7f030009;
        public static final int help=0x7f03000a;
        public static final int icon_picker=0x7f03000b;
        public static final int list_item_view=0x7f03000c;
        public static final int list_task_view=0x7f03000d;
        public static final int preferences_appearance=0x7f03000e;
        public static final int preferences_clean=0x7f03000f;
        public static final int project_editor=0x7f030010;
        public static final int projects=0x7f030011;
        public static final int tabbed_due_tasks=0x7f030012;
        public static final int task_editor=0x7f030013;
        public static final int task_list=0x7f030014;
        public static final int task_view=0x7f030015;
        public static final int top_level=0x7f030016;
        public static final int welcome=0x7f030017;
    }
    public static final class string {
        /**   Activity titles 
         */
        public static final int app_name=0x7f070000;
        public static final int archived_title=0x7f07003a;
        public static final int cancel_button_title=0x7f07002a;
        public static final int clean_inbox_button_title=0x7f070051;
        public static final int clean_inbox_message=0x7f07005b;
        public static final int clean_slate_button_title=0x7f070052;
        public static final int clean_slate_message=0x7f07005c;
        public static final int clean_slate_title=0x7f070035;
        public static final int clean_task_message=0x7f07005a;
        public static final int cleanup_preferences=0x7f07004b;
        public static final int clear_button_title=0x7f070025;
        /**   project & context edit screens 
         */
        public static final int colour_title=0x7f070039;
        public static final int completed_title=0x7f070038;
        public static final int context_icon_title=0x7f070042;
        public static final int context_name=0x7f07002f;
        public static final int context_name_title=0x7f070043;
        public static final int context_title=0x7f070022;
        /**   Calendar screen 
         */
        public static final int day_button_title=0x7f07003e;
        public static final int default_context_title=0x7f07003d;
        public static final int delete_completed_button_title=0x7f070050;
        public static final int delete_completed_title=0x7f07004f;
        public static final int delete_warning=0x7f070059;
        /**   task edit screen 
         */
        public static final int description_title=0x7f070036;
        public static final int details_title=0x7f070023;
        public static final int dialog_title_cleanup_preference=0x7f07004e;
        /**   preferences screen 
         */
        public static final int display_task_list_title=0x7f070041;
        public static final int done_button_title=0x7f070029;
        public static final int due_date_title=0x7f070037;
        public static final int edit_button_title=0x7f070026;
        public static final int error_message=0x7f07005e;
        public static final int error_title=0x7f07005d;
        public static final int extras_button_title=0x7f070027;
        public static final int help0=0x7f070062;
        public static final int help1=0x7f070063;
        public static final int help2=0x7f070064;
        public static final int help3=0x7f070065;
        public static final int help4=0x7f070066;
        public static final int help5=0x7f070067;
        public static final int help6=0x7f070068;
        public static final int help7=0x7f070069;
        public static final int help8=0x7f07006a;
        public static final int icon_title=0x7f07003b;
        public static final int info_title=0x7f07002c;
        public static final int layout_preferences=0x7f070044;
        public static final int menu_complete=0x7f070018;
        public static final int menu_delete=0x7f070017;
        public static final int menu_discard=0x7f07001d;
        public static final int menu_help=0x7f070020;
        public static final int menu_insert=0x7f07001b;
        public static final int menu_move_down=0x7f07001a;
        public static final int menu_move_up=0x7f070019;
        public static final int menu_preferences=0x7f07001f;
        public static final int menu_revert=0x7f07001c;
        /**   Option menu 
         */
        public static final int menu_save=0x7f070016;
        public static final int menu_view=0x7f07001e;
        public static final int month_button_title=0x7f070040;
        public static final int name_title=0x7f07003c;
        public static final int no_contexts=0x7f070058;
        /**   messages 
         */
        public static final int no_due_date=0x7f070053;
        public static final int no_due_tasks=0x7f070056;
        public static final int no_icon=0x7f070054;
        public static final int no_projects=0x7f070057;
        public static final int no_tasks=0x7f070055;
        public static final int nothing=0x7f070030;
        public static final int project_name=0x7f07002e;
        /**   general purpose 
         */
        public static final int project_title=0x7f070021;
        /**   Welcome screen 
         */
        public static final int sample_data_title=0x7f070034;
        public static final int save_button_title=0x7f070028;
        public static final int set_button_title=0x7f070024;
        public static final int summary_action_appearance_preference=0x7f07004a;
        public static final int summary_cleanup_preference=0x7f07004d;
        public static final int summary_context_view_preference=0x7f070048;
        public static final int summary_project_view_preference=0x7f070046;
        public static final int task_name=0x7f07002d;
        public static final int title_action_appearance_preference=0x7f070049;
        public static final int title_calendar=0x7f070013;
        public static final int title_cleanup_preference=0x7f07004c;
        public static final int title_context=0x7f070003;
        public static final int title_context_tasks=0x7f070015;
        public static final int title_context_view_preference=0x7f070047;
        public static final int title_due_tasks=0x7f070005;
        public static final int title_edit_context=0x7f07000c;
        public static final int title_edit_project=0x7f07000a;
        public static final int title_edit_task=0x7f070007;
        public static final int title_help=0x7f070011;
        public static final int title_icon_picker=0x7f070012;
        public static final int title_inbox=0x7f070001;
        public static final int title_new_context=0x7f07000b;
        public static final int title_new_project=0x7f070009;
        public static final int title_new_task=0x7f070006;
        public static final int title_next_tasks=0x7f070004;
        public static final int title_preferences=0x7f07000e;
        public static final int title_preferences_appearance=0x7f07000f;
        public static final int title_preferences_clean=0x7f070010;
        public static final int title_project=0x7f070002;
        public static final int title_project_tasks=0x7f070014;
        public static final int title_project_view_preference=0x7f070045;
        public static final int title_task_extras=0x7f07000d;
        public static final int title_view_task=0x7f070008;
        public static final int today=0x7f070032;
        public static final int undefined=0x7f070031;
        public static final int warning_title=0x7f07002b;
        public static final int week_button_title=0x7f07003f;
        public static final int welcome1=0x7f07005f;
        public static final int welcome2=0x7f070060;
        public static final int welcome3=0x7f070061;
        public static final int yesterday=0x7f070033;
    }
    public static final class style {
        public static final int ShuffleTheme=0x7f080000;
        public static final int activity=0x7f080001;
        public static final int autocomplete_text=0x7f08000d;
        public static final int centered_row=0x7f080014;
        public static final int context=0x7f080009;
        public static final int detail_label=0x7f08000e;
        public static final int dialog_editor=0x7f080002;
        public static final int due_date=0x7f080013;
        public static final int editable_text=0x7f080008;
        public static final int editor=0x7f080003;
        public static final int image=0x7f080006;
        public static final int label=0x7f08000a;
        public static final int list=0x7f080005;
        public static final int preference_checkbox=0x7f08000c;
        public static final int preference_label=0x7f08000b;
        public static final int sub_text_1=0x7f08000f;
        public static final int sub_text_2=0x7f080010;
        public static final int text=0x7f080007;
        public static final int top_row=0x7f080015;
        public static final int view_label=0x7f080012;
        public static final int view_text=0x7f080011;
        public static final int viewer=0x7f080004;
    }
    public static final class xml {
        public static final int preferences=0x7f050000;
    }
}
