// Generated by the protocol buffer compiler.  DO NOT EDIT!

package org.dodgybits.shuffle.dto;

public final class ShuffleProtos {
  private ShuffleProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Context extends
      com.google.protobuf.GeneratedMessage {
    // Use Context.newBuilder() to construct.
    private Context() {}
    
    private static final Context defaultInstance = new Context();
    public static Context getDefaultInstance() {
      return defaultInstance;
    }
    
    public Context getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.dodgybits.shuffle.dto.ShuffleProtos.internal_static_shuffle_Context_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.dodgybits.shuffle.dto.ShuffleProtos.internal_static_shuffle_Context_fieldAccessorTable;
    }
    
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private long id_ = 0L;
    public boolean hasId() { return hasId; }
    public long getId() { return id_; }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional int32 colourIndex = 3;
    public static final int COLOURINDEX_FIELD_NUMBER = 3;
    private boolean hasColourIndex;
    private int colourIndex_ = 0;
    public boolean hasColourIndex() { return hasColourIndex; }
    public int getColourIndex() { return colourIndex_; }
    
    // optional string icon = 4;
    public static final int ICON_FIELD_NUMBER = 4;
    private boolean hasIcon;
    private java.lang.String icon_ = "";
    public boolean hasIcon() { return hasIcon; }
    public java.lang.String getIcon() { return icon_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasId) return false;
      if (!hasName) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasId()) {
        output.writeInt64(1, getId());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      if (hasColourIndex()) {
        output.writeInt32(3, getColourIndex());
      }
      if (hasIcon()) {
        output.writeString(4, getIcon());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, getId());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      if (hasColourIndex()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getColourIndex());
      }
      if (hasIcon()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getIcon());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Context parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Context parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Context parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Context parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Context parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Context parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Context parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Context parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Context parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Context parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(org.dodgybits.shuffle.dto.ShuffleProtos.Context prototype) {
      return new Builder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using org.dodgybits.shuffle.dto.ShuffleProtos.Context.newBuilder()
      private Builder() {}
      
      org.dodgybits.shuffle.dto.ShuffleProtos.Context result = new org.dodgybits.shuffle.dto.ShuffleProtos.Context();
      
      @Override
      protected org.dodgybits.shuffle.dto.ShuffleProtos.Context internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new org.dodgybits.shuffle.dto.ShuffleProtos.Context();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.dodgybits.shuffle.dto.ShuffleProtos.Context.getDescriptor();
      }
      
      public org.dodgybits.shuffle.dto.ShuffleProtos.Context getDefaultInstanceForType() {
        return org.dodgybits.shuffle.dto.ShuffleProtos.Context.getDefaultInstance();
      }
      
      public org.dodgybits.shuffle.dto.ShuffleProtos.Context build() {
        if (result != null && !isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private org.dodgybits.shuffle.dto.ShuffleProtos.Context buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.dodgybits.shuffle.dto.ShuffleProtos.Context buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");  }
        org.dodgybits.shuffle.dto.ShuffleProtos.Context returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.dodgybits.shuffle.dto.ShuffleProtos.Context) {
          return mergeFrom((org.dodgybits.shuffle.dto.ShuffleProtos.Context)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.dodgybits.shuffle.dto.ShuffleProtos.Context other) {
        if (other == org.dodgybits.shuffle.dto.ShuffleProtos.Context.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasColourIndex()) {
          setColourIndex(other.getColourIndex());
        }
        if (other.hasIcon()) {
          setIcon(other.getIcon());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt64());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
            case 24: {
              setColourIndex(input.readInt32());
              break;
            }
            case 34: {
              setIcon(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required int64 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public long getId() {
        return result.getId();
      }
      public Builder setId(long value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0L;
        return this;
      }
      
      // required string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      // optional int32 colourIndex = 3;
      public boolean hasColourIndex() {
        return result.hasColourIndex();
      }
      public int getColourIndex() {
        return result.getColourIndex();
      }
      public Builder setColourIndex(int value) {
        result.hasColourIndex = true;
        result.colourIndex_ = value;
        return this;
      }
      public Builder clearColourIndex() {
        result.hasColourIndex = false;
        result.colourIndex_ = 0;
        return this;
      }
      
      // optional string icon = 4;
      public boolean hasIcon() {
        return result.hasIcon();
      }
      public java.lang.String getIcon() {
        return result.getIcon();
      }
      public Builder setIcon(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasIcon = true;
        result.icon_ = value;
        return this;
      }
      public Builder clearIcon() {
        result.hasIcon = false;
        result.icon_ = "";
        return this;
      }
    }
    
    static {
      org.dodgybits.shuffle.dto.ShuffleProtos.getDescriptor();
    }
  }
  
  public static final class Project extends
      com.google.protobuf.GeneratedMessage {
    // Use Project.newBuilder() to construct.
    private Project() {}
    
    private static final Project defaultInstance = new Project();
    public static Project getDefaultInstance() {
      return defaultInstance;
    }
    
    public Project getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.dodgybits.shuffle.dto.ShuffleProtos.internal_static_shuffle_Project_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.dodgybits.shuffle.dto.ShuffleProtos.internal_static_shuffle_Project_fieldAccessorTable;
    }
    
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private long id_ = 0L;
    public boolean hasId() { return hasId; }
    public long getId() { return id_; }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional int64 defaultContextId = 3;
    public static final int DEFAULTCONTEXTID_FIELD_NUMBER = 3;
    private boolean hasDefaultContextId;
    private long defaultContextId_ = 0L;
    public boolean hasDefaultContextId() { return hasDefaultContextId; }
    public long getDefaultContextId() { return defaultContextId_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasId) return false;
      if (!hasName) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasId()) {
        output.writeInt64(1, getId());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      if (hasDefaultContextId()) {
        output.writeInt64(3, getDefaultContextId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, getId());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      if (hasDefaultContextId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, getDefaultContextId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Project parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Project parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Project parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Project parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Project parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Project parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Project parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Project parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Project parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Project parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(org.dodgybits.shuffle.dto.ShuffleProtos.Project prototype) {
      return new Builder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using org.dodgybits.shuffle.dto.ShuffleProtos.Project.newBuilder()
      private Builder() {}
      
      org.dodgybits.shuffle.dto.ShuffleProtos.Project result = new org.dodgybits.shuffle.dto.ShuffleProtos.Project();
      
      @Override
      protected org.dodgybits.shuffle.dto.ShuffleProtos.Project internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new org.dodgybits.shuffle.dto.ShuffleProtos.Project();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.dodgybits.shuffle.dto.ShuffleProtos.Project.getDescriptor();
      }
      
      public org.dodgybits.shuffle.dto.ShuffleProtos.Project getDefaultInstanceForType() {
        return org.dodgybits.shuffle.dto.ShuffleProtos.Project.getDefaultInstance();
      }
      
      public org.dodgybits.shuffle.dto.ShuffleProtos.Project build() {
        if (result != null && !isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private org.dodgybits.shuffle.dto.ShuffleProtos.Project buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.dodgybits.shuffle.dto.ShuffleProtos.Project buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");  }
        org.dodgybits.shuffle.dto.ShuffleProtos.Project returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.dodgybits.shuffle.dto.ShuffleProtos.Project) {
          return mergeFrom((org.dodgybits.shuffle.dto.ShuffleProtos.Project)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.dodgybits.shuffle.dto.ShuffleProtos.Project other) {
        if (other == org.dodgybits.shuffle.dto.ShuffleProtos.Project.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasDefaultContextId()) {
          setDefaultContextId(other.getDefaultContextId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt64());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
            case 24: {
              setDefaultContextId(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // required int64 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public long getId() {
        return result.getId();
      }
      public Builder setId(long value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0L;
        return this;
      }
      
      // required string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      // optional int64 defaultContextId = 3;
      public boolean hasDefaultContextId() {
        return result.hasDefaultContextId();
      }
      public long getDefaultContextId() {
        return result.getDefaultContextId();
      }
      public Builder setDefaultContextId(long value) {
        result.hasDefaultContextId = true;
        result.defaultContextId_ = value;
        return this;
      }
      public Builder clearDefaultContextId() {
        result.hasDefaultContextId = false;
        result.defaultContextId_ = 0L;
        return this;
      }
    }
    
    static {
      org.dodgybits.shuffle.dto.ShuffleProtos.getDescriptor();
    }
  }
  
  public static final class Task extends
      com.google.protobuf.GeneratedMessage {
    // Use Task.newBuilder() to construct.
    private Task() {}
    
    private static final Task defaultInstance = new Task();
    public static Task getDefaultInstance() {
      return defaultInstance;
    }
    
    public Task getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.dodgybits.shuffle.dto.ShuffleProtos.internal_static_shuffle_Task_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.dodgybits.shuffle.dto.ShuffleProtos.internal_static_shuffle_Task_fieldAccessorTable;
    }
    
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private long id_ = 0L;
    public boolean hasId() { return hasId; }
    public long getId() { return id_; }
    
    // required string description = 2;
    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private boolean hasDescription;
    private java.lang.String description_ = "";
    public boolean hasDescription() { return hasDescription; }
    public java.lang.String getDescription() { return description_; }
    
    // optional string details = 3;
    public static final int DETAILS_FIELD_NUMBER = 3;
    private boolean hasDetails;
    private java.lang.String details_ = "";
    public boolean hasDetails() { return hasDetails; }
    public java.lang.String getDetails() { return details_; }
    
    // optional int64 contextId = 4;
    public static final int CONTEXTID_FIELD_NUMBER = 4;
    private boolean hasContextId;
    private long contextId_ = 0L;
    public boolean hasContextId() { return hasContextId; }
    public long getContextId() { return contextId_; }
    
    // optional int64 projectId = 5;
    public static final int PROJECTID_FIELD_NUMBER = 5;
    private boolean hasProjectId;
    private long projectId_ = 0L;
    public boolean hasProjectId() { return hasProjectId; }
    public long getProjectId() { return projectId_; }
    
    // optional .shuffle.Date created = 6;
    public static final int CREATED_FIELD_NUMBER = 6;
    private boolean hasCreated;
    private org.dodgybits.shuffle.dto.ShuffleProtos.Date created_ = org.dodgybits.shuffle.dto.ShuffleProtos.Date.getDefaultInstance();
    public boolean hasCreated() { return hasCreated; }
    public org.dodgybits.shuffle.dto.ShuffleProtos.Date getCreated() { return created_; }
    
    // optional .shuffle.Date modified = 7;
    public static final int MODIFIED_FIELD_NUMBER = 7;
    private boolean hasModified;
    private org.dodgybits.shuffle.dto.ShuffleProtos.Date modified_ = org.dodgybits.shuffle.dto.ShuffleProtos.Date.getDefaultInstance();
    public boolean hasModified() { return hasModified; }
    public org.dodgybits.shuffle.dto.ShuffleProtos.Date getModified() { return modified_; }
    
    // optional .shuffle.Date startDate = 8;
    public static final int STARTDATE_FIELD_NUMBER = 8;
    private boolean hasStartDate;
    private org.dodgybits.shuffle.dto.ShuffleProtos.Date startDate_ = org.dodgybits.shuffle.dto.ShuffleProtos.Date.getDefaultInstance();
    public boolean hasStartDate() { return hasStartDate; }
    public org.dodgybits.shuffle.dto.ShuffleProtos.Date getStartDate() { return startDate_; }
    
    // optional .shuffle.Date dueDate = 9;
    public static final int DUEDATE_FIELD_NUMBER = 9;
    private boolean hasDueDate;
    private org.dodgybits.shuffle.dto.ShuffleProtos.Date dueDate_ = org.dodgybits.shuffle.dto.ShuffleProtos.Date.getDefaultInstance();
    public boolean hasDueDate() { return hasDueDate; }
    public org.dodgybits.shuffle.dto.ShuffleProtos.Date getDueDate() { return dueDate_; }
    
    // optional string timezone = 10;
    public static final int TIMEZONE_FIELD_NUMBER = 10;
    private boolean hasTimezone;
    private java.lang.String timezone_ = "";
    public boolean hasTimezone() { return hasTimezone; }
    public java.lang.String getTimezone() { return timezone_; }
    
    // optional bool allDay = 11;
    public static final int ALLDAY_FIELD_NUMBER = 11;
    private boolean hasAllDay;
    private boolean allDay_ = false;
    public boolean hasAllDay() { return hasAllDay; }
    public boolean getAllDay() { return allDay_; }
    
    // optional int64 calEventId = 12;
    public static final int CALEVENTID_FIELD_NUMBER = 12;
    private boolean hasCalEventId;
    private long calEventId_ = 0L;
    public boolean hasCalEventId() { return hasCalEventId; }
    public long getCalEventId() { return calEventId_; }
    
    // optional int32 order = 13;
    public static final int ORDER_FIELD_NUMBER = 13;
    private boolean hasOrder;
    private int order_ = 0;
    public boolean hasOrder() { return hasOrder; }
    public int getOrder() { return order_; }
    
    // optional bool complete = 14;
    public static final int COMPLETE_FIELD_NUMBER = 14;
    private boolean hasComplete;
    private boolean complete_ = false;
    public boolean hasComplete() { return hasComplete; }
    public boolean getComplete() { return complete_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasId) return false;
      if (!hasDescription) return false;
      if (hasCreated()) {
        if (!getCreated().isInitialized()) return false;
      }
      if (hasModified()) {
        if (!getModified().isInitialized()) return false;
      }
      if (hasStartDate()) {
        if (!getStartDate().isInitialized()) return false;
      }
      if (hasDueDate()) {
        if (!getDueDate().isInitialized()) return false;
      }
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasId()) {
        output.writeInt64(1, getId());
      }
      if (hasDescription()) {
        output.writeString(2, getDescription());
      }
      if (hasDetails()) {
        output.writeString(3, getDetails());
      }
      if (hasContextId()) {
        output.writeInt64(4, getContextId());
      }
      if (hasProjectId()) {
        output.writeInt64(5, getProjectId());
      }
      if (hasCreated()) {
        output.writeMessage(6, getCreated());
      }
      if (hasModified()) {
        output.writeMessage(7, getModified());
      }
      if (hasStartDate()) {
        output.writeMessage(8, getStartDate());
      }
      if (hasDueDate()) {
        output.writeMessage(9, getDueDate());
      }
      if (hasTimezone()) {
        output.writeString(10, getTimezone());
      }
      if (hasAllDay()) {
        output.writeBool(11, getAllDay());
      }
      if (hasCalEventId()) {
        output.writeInt64(12, getCalEventId());
      }
      if (hasOrder()) {
        output.writeInt32(13, getOrder());
      }
      if (hasComplete()) {
        output.writeBool(14, getComplete());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, getId());
      }
      if (hasDescription()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getDescription());
      }
      if (hasDetails()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getDetails());
      }
      if (hasContextId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, getContextId());
      }
      if (hasProjectId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, getProjectId());
      }
      if (hasCreated()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getCreated());
      }
      if (hasModified()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getModified());
      }
      if (hasStartDate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getStartDate());
      }
      if (hasDueDate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getDueDate());
      }
      if (hasTimezone()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getTimezone());
      }
      if (hasAllDay()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, getAllDay());
      }
      if (hasCalEventId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, getCalEventId());
      }
      if (hasOrder()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, getOrder());
      }
      if (hasComplete()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, getComplete());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Task parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Task parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Task parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Task parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Task parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Task parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Task parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Task parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Task parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Task parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(org.dodgybits.shuffle.dto.ShuffleProtos.Task prototype) {
      return new Builder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using org.dodgybits.shuffle.dto.ShuffleProtos.Task.newBuilder()
      private Builder() {}
      
      org.dodgybits.shuffle.dto.ShuffleProtos.Task result = new org.dodgybits.shuffle.dto.ShuffleProtos.Task();
      
      @Override
      protected org.dodgybits.shuffle.dto.ShuffleProtos.Task internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new org.dodgybits.shuffle.dto.ShuffleProtos.Task();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.dodgybits.shuffle.dto.ShuffleProtos.Task.getDescriptor();
      }
      
      public org.dodgybits.shuffle.dto.ShuffleProtos.Task getDefaultInstanceForType() {
        return org.dodgybits.shuffle.dto.ShuffleProtos.Task.getDefaultInstance();
      }
      
      public org.dodgybits.shuffle.dto.ShuffleProtos.Task build() {
        if (result != null && !isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private org.dodgybits.shuffle.dto.ShuffleProtos.Task buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.dodgybits.shuffle.dto.ShuffleProtos.Task buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");  }
        org.dodgybits.shuffle.dto.ShuffleProtos.Task returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.dodgybits.shuffle.dto.ShuffleProtos.Task) {
          return mergeFrom((org.dodgybits.shuffle.dto.ShuffleProtos.Task)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.dodgybits.shuffle.dto.ShuffleProtos.Task other) {
        if (other == org.dodgybits.shuffle.dto.ShuffleProtos.Task.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasDetails()) {
          setDetails(other.getDetails());
        }
        if (other.hasContextId()) {
          setContextId(other.getContextId());
        }
        if (other.hasProjectId()) {
          setProjectId(other.getProjectId());
        }
        if (other.hasCreated()) {
          mergeCreated(other.getCreated());
        }
        if (other.hasModified()) {
          mergeModified(other.getModified());
        }
        if (other.hasStartDate()) {
          mergeStartDate(other.getStartDate());
        }
        if (other.hasDueDate()) {
          mergeDueDate(other.getDueDate());
        }
        if (other.hasTimezone()) {
          setTimezone(other.getTimezone());
        }
        if (other.hasAllDay()) {
          setAllDay(other.getAllDay());
        }
        if (other.hasCalEventId()) {
          setCalEventId(other.getCalEventId());
        }
        if (other.hasOrder()) {
          setOrder(other.getOrder());
        }
        if (other.hasComplete()) {
          setComplete(other.getComplete());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt64());
              break;
            }
            case 18: {
              setDescription(input.readString());
              break;
            }
            case 26: {
              setDetails(input.readString());
              break;
            }
            case 32: {
              setContextId(input.readInt64());
              break;
            }
            case 40: {
              setProjectId(input.readInt64());
              break;
            }
            case 50: {
              org.dodgybits.shuffle.dto.ShuffleProtos.Date.Builder subBuilder = org.dodgybits.shuffle.dto.ShuffleProtos.Date.newBuilder();
              if (hasCreated()) {
                subBuilder.mergeFrom(getCreated());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCreated(subBuilder.buildPartial());
              break;
            }
            case 58: {
              org.dodgybits.shuffle.dto.ShuffleProtos.Date.Builder subBuilder = org.dodgybits.shuffle.dto.ShuffleProtos.Date.newBuilder();
              if (hasModified()) {
                subBuilder.mergeFrom(getModified());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setModified(subBuilder.buildPartial());
              break;
            }
            case 66: {
              org.dodgybits.shuffle.dto.ShuffleProtos.Date.Builder subBuilder = org.dodgybits.shuffle.dto.ShuffleProtos.Date.newBuilder();
              if (hasStartDate()) {
                subBuilder.mergeFrom(getStartDate());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setStartDate(subBuilder.buildPartial());
              break;
            }
            case 74: {
              org.dodgybits.shuffle.dto.ShuffleProtos.Date.Builder subBuilder = org.dodgybits.shuffle.dto.ShuffleProtos.Date.newBuilder();
              if (hasDueDate()) {
                subBuilder.mergeFrom(getDueDate());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setDueDate(subBuilder.buildPartial());
              break;
            }
            case 82: {
              setTimezone(input.readString());
              break;
            }
            case 88: {
              setAllDay(input.readBool());
              break;
            }
            case 96: {
              setCalEventId(input.readInt64());
              break;
            }
            case 104: {
              setOrder(input.readInt32());
              break;
            }
            case 112: {
              setComplete(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // required int64 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public long getId() {
        return result.getId();
      }
      public Builder setId(long value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0L;
        return this;
      }
      
      // required string description = 2;
      public boolean hasDescription() {
        return result.hasDescription();
      }
      public java.lang.String getDescription() {
        return result.getDescription();
      }
      public Builder setDescription(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDescription = true;
        result.description_ = value;
        return this;
      }
      public Builder clearDescription() {
        result.hasDescription = false;
        result.description_ = "";
        return this;
      }
      
      // optional string details = 3;
      public boolean hasDetails() {
        return result.hasDetails();
      }
      public java.lang.String getDetails() {
        return result.getDetails();
      }
      public Builder setDetails(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDetails = true;
        result.details_ = value;
        return this;
      }
      public Builder clearDetails() {
        result.hasDetails = false;
        result.details_ = "";
        return this;
      }
      
      // optional int64 contextId = 4;
      public boolean hasContextId() {
        return result.hasContextId();
      }
      public long getContextId() {
        return result.getContextId();
      }
      public Builder setContextId(long value) {
        result.hasContextId = true;
        result.contextId_ = value;
        return this;
      }
      public Builder clearContextId() {
        result.hasContextId = false;
        result.contextId_ = 0L;
        return this;
      }
      
      // optional int64 projectId = 5;
      public boolean hasProjectId() {
        return result.hasProjectId();
      }
      public long getProjectId() {
        return result.getProjectId();
      }
      public Builder setProjectId(long value) {
        result.hasProjectId = true;
        result.projectId_ = value;
        return this;
      }
      public Builder clearProjectId() {
        result.hasProjectId = false;
        result.projectId_ = 0L;
        return this;
      }
      
      // optional .shuffle.Date created = 6;
      public boolean hasCreated() {
        return result.hasCreated();
      }
      public org.dodgybits.shuffle.dto.ShuffleProtos.Date getCreated() {
        return result.getCreated();
      }
      public Builder setCreated(org.dodgybits.shuffle.dto.ShuffleProtos.Date value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCreated = true;
        result.created_ = value;
        return this;
      }
      public Builder setCreated(org.dodgybits.shuffle.dto.ShuffleProtos.Date.Builder builderForValue) {
        result.hasCreated = true;
        result.created_ = builderForValue.build();
        return this;
      }
      public Builder mergeCreated(org.dodgybits.shuffle.dto.ShuffleProtos.Date value) {
        if (result.hasCreated() &&
            result.created_ != org.dodgybits.shuffle.dto.ShuffleProtos.Date.getDefaultInstance()) {
          result.created_ =
            org.dodgybits.shuffle.dto.ShuffleProtos.Date.newBuilder(result.created_).mergeFrom(value).buildPartial();
        } else {
          result.created_ = value;
        }
        result.hasCreated = true;
        return this;
      }
      public Builder clearCreated() {
        result.hasCreated = false;
        result.created_ = org.dodgybits.shuffle.dto.ShuffleProtos.Date.getDefaultInstance();
        return this;
      }
      
      // optional .shuffle.Date modified = 7;
      public boolean hasModified() {
        return result.hasModified();
      }
      public org.dodgybits.shuffle.dto.ShuffleProtos.Date getModified() {
        return result.getModified();
      }
      public Builder setModified(org.dodgybits.shuffle.dto.ShuffleProtos.Date value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasModified = true;
        result.modified_ = value;
        return this;
      }
      public Builder setModified(org.dodgybits.shuffle.dto.ShuffleProtos.Date.Builder builderForValue) {
        result.hasModified = true;
        result.modified_ = builderForValue.build();
        return this;
      }
      public Builder mergeModified(org.dodgybits.shuffle.dto.ShuffleProtos.Date value) {
        if (result.hasModified() &&
            result.modified_ != org.dodgybits.shuffle.dto.ShuffleProtos.Date.getDefaultInstance()) {
          result.modified_ =
            org.dodgybits.shuffle.dto.ShuffleProtos.Date.newBuilder(result.modified_).mergeFrom(value).buildPartial();
        } else {
          result.modified_ = value;
        }
        result.hasModified = true;
        return this;
      }
      public Builder clearModified() {
        result.hasModified = false;
        result.modified_ = org.dodgybits.shuffle.dto.ShuffleProtos.Date.getDefaultInstance();
        return this;
      }
      
      // optional .shuffle.Date startDate = 8;
      public boolean hasStartDate() {
        return result.hasStartDate();
      }
      public org.dodgybits.shuffle.dto.ShuffleProtos.Date getStartDate() {
        return result.getStartDate();
      }
      public Builder setStartDate(org.dodgybits.shuffle.dto.ShuffleProtos.Date value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasStartDate = true;
        result.startDate_ = value;
        return this;
      }
      public Builder setStartDate(org.dodgybits.shuffle.dto.ShuffleProtos.Date.Builder builderForValue) {
        result.hasStartDate = true;
        result.startDate_ = builderForValue.build();
        return this;
      }
      public Builder mergeStartDate(org.dodgybits.shuffle.dto.ShuffleProtos.Date value) {
        if (result.hasStartDate() &&
            result.startDate_ != org.dodgybits.shuffle.dto.ShuffleProtos.Date.getDefaultInstance()) {
          result.startDate_ =
            org.dodgybits.shuffle.dto.ShuffleProtos.Date.newBuilder(result.startDate_).mergeFrom(value).buildPartial();
        } else {
          result.startDate_ = value;
        }
        result.hasStartDate = true;
        return this;
      }
      public Builder clearStartDate() {
        result.hasStartDate = false;
        result.startDate_ = org.dodgybits.shuffle.dto.ShuffleProtos.Date.getDefaultInstance();
        return this;
      }
      
      // optional .shuffle.Date dueDate = 9;
      public boolean hasDueDate() {
        return result.hasDueDate();
      }
      public org.dodgybits.shuffle.dto.ShuffleProtos.Date getDueDate() {
        return result.getDueDate();
      }
      public Builder setDueDate(org.dodgybits.shuffle.dto.ShuffleProtos.Date value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasDueDate = true;
        result.dueDate_ = value;
        return this;
      }
      public Builder setDueDate(org.dodgybits.shuffle.dto.ShuffleProtos.Date.Builder builderForValue) {
        result.hasDueDate = true;
        result.dueDate_ = builderForValue.build();
        return this;
      }
      public Builder mergeDueDate(org.dodgybits.shuffle.dto.ShuffleProtos.Date value) {
        if (result.hasDueDate() &&
            result.dueDate_ != org.dodgybits.shuffle.dto.ShuffleProtos.Date.getDefaultInstance()) {
          result.dueDate_ =
            org.dodgybits.shuffle.dto.ShuffleProtos.Date.newBuilder(result.dueDate_).mergeFrom(value).buildPartial();
        } else {
          result.dueDate_ = value;
        }
        result.hasDueDate = true;
        return this;
      }
      public Builder clearDueDate() {
        result.hasDueDate = false;
        result.dueDate_ = org.dodgybits.shuffle.dto.ShuffleProtos.Date.getDefaultInstance();
        return this;
      }
      
      // optional string timezone = 10;
      public boolean hasTimezone() {
        return result.hasTimezone();
      }
      public java.lang.String getTimezone() {
        return result.getTimezone();
      }
      public Builder setTimezone(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTimezone = true;
        result.timezone_ = value;
        return this;
      }
      public Builder clearTimezone() {
        result.hasTimezone = false;
        result.timezone_ = "";
        return this;
      }
      
      // optional bool allDay = 11;
      public boolean hasAllDay() {
        return result.hasAllDay();
      }
      public boolean getAllDay() {
        return result.getAllDay();
      }
      public Builder setAllDay(boolean value) {
        result.hasAllDay = true;
        result.allDay_ = value;
        return this;
      }
      public Builder clearAllDay() {
        result.hasAllDay = false;
        result.allDay_ = false;
        return this;
      }
      
      // optional int64 calEventId = 12;
      public boolean hasCalEventId() {
        return result.hasCalEventId();
      }
      public long getCalEventId() {
        return result.getCalEventId();
      }
      public Builder setCalEventId(long value) {
        result.hasCalEventId = true;
        result.calEventId_ = value;
        return this;
      }
      public Builder clearCalEventId() {
        result.hasCalEventId = false;
        result.calEventId_ = 0L;
        return this;
      }
      
      // optional int32 order = 13;
      public boolean hasOrder() {
        return result.hasOrder();
      }
      public int getOrder() {
        return result.getOrder();
      }
      public Builder setOrder(int value) {
        result.hasOrder = true;
        result.order_ = value;
        return this;
      }
      public Builder clearOrder() {
        result.hasOrder = false;
        result.order_ = 0;
        return this;
      }
      
      // optional bool complete = 14;
      public boolean hasComplete() {
        return result.hasComplete();
      }
      public boolean getComplete() {
        return result.getComplete();
      }
      public Builder setComplete(boolean value) {
        result.hasComplete = true;
        result.complete_ = value;
        return this;
      }
      public Builder clearComplete() {
        result.hasComplete = false;
        result.complete_ = false;
        return this;
      }
    }
    
    static {
      org.dodgybits.shuffle.dto.ShuffleProtos.getDescriptor();
    }
  }
  
  public static final class Date extends
      com.google.protobuf.GeneratedMessage {
    // Use Date.newBuilder() to construct.
    private Date() {}
    
    private static final Date defaultInstance = new Date();
    public static Date getDefaultInstance() {
      return defaultInstance;
    }
    
    public Date getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.dodgybits.shuffle.dto.ShuffleProtos.internal_static_shuffle_Date_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.dodgybits.shuffle.dto.ShuffleProtos.internal_static_shuffle_Date_fieldAccessorTable;
    }
    
    // required int64 millis = 1;
    public static final int MILLIS_FIELD_NUMBER = 1;
    private boolean hasMillis;
    private long millis_ = 0L;
    public boolean hasMillis() { return hasMillis; }
    public long getMillis() { return millis_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasMillis) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasMillis()) {
        output.writeInt64(1, getMillis());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMillis()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, getMillis());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Date parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Date parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Date parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Date parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Date parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Date parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Date parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Date parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Date parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Date parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(org.dodgybits.shuffle.dto.ShuffleProtos.Date prototype) {
      return new Builder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using org.dodgybits.shuffle.dto.ShuffleProtos.Date.newBuilder()
      private Builder() {}
      
      org.dodgybits.shuffle.dto.ShuffleProtos.Date result = new org.dodgybits.shuffle.dto.ShuffleProtos.Date();
      
      @Override
      protected org.dodgybits.shuffle.dto.ShuffleProtos.Date internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new org.dodgybits.shuffle.dto.ShuffleProtos.Date();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.dodgybits.shuffle.dto.ShuffleProtos.Date.getDescriptor();
      }
      
      public org.dodgybits.shuffle.dto.ShuffleProtos.Date getDefaultInstanceForType() {
        return org.dodgybits.shuffle.dto.ShuffleProtos.Date.getDefaultInstance();
      }
      
      public org.dodgybits.shuffle.dto.ShuffleProtos.Date build() {
        if (result != null && !isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private org.dodgybits.shuffle.dto.ShuffleProtos.Date buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.dodgybits.shuffle.dto.ShuffleProtos.Date buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");  }
        org.dodgybits.shuffle.dto.ShuffleProtos.Date returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.dodgybits.shuffle.dto.ShuffleProtos.Date) {
          return mergeFrom((org.dodgybits.shuffle.dto.ShuffleProtos.Date)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.dodgybits.shuffle.dto.ShuffleProtos.Date other) {
        if (other == org.dodgybits.shuffle.dto.ShuffleProtos.Date.getDefaultInstance()) return this;
        if (other.hasMillis()) {
          setMillis(other.getMillis());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setMillis(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // required int64 millis = 1;
      public boolean hasMillis() {
        return result.hasMillis();
      }
      public long getMillis() {
        return result.getMillis();
      }
      public Builder setMillis(long value) {
        result.hasMillis = true;
        result.millis_ = value;
        return this;
      }
      public Builder clearMillis() {
        result.hasMillis = false;
        result.millis_ = 0L;
        return this;
      }
    }
    
    static {
      org.dodgybits.shuffle.dto.ShuffleProtos.getDescriptor();
    }
  }
  
  public static final class Catalogue extends
      com.google.protobuf.GeneratedMessage {
    // Use Catalogue.newBuilder() to construct.
    private Catalogue() {}
    
    private static final Catalogue defaultInstance = new Catalogue();
    public static Catalogue getDefaultInstance() {
      return defaultInstance;
    }
    
    public Catalogue getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.dodgybits.shuffle.dto.ShuffleProtos.internal_static_shuffle_Catalogue_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.dodgybits.shuffle.dto.ShuffleProtos.internal_static_shuffle_Catalogue_fieldAccessorTable;
    }
    
    // repeated .shuffle.Context context = 1;
    public static final int CONTEXT_FIELD_NUMBER = 1;
    private java.util.List<org.dodgybits.shuffle.dto.ShuffleProtos.Context> context_ =
      java.util.Collections.emptyList();
    public java.util.List<org.dodgybits.shuffle.dto.ShuffleProtos.Context> getContextList() {
      return context_;
    }
    public int getContextCount() { return context_.size(); }
    public org.dodgybits.shuffle.dto.ShuffleProtos.Context getContext(int index) {
      return context_.get(index);
    }
    
    // repeated .shuffle.Project project = 2;
    public static final int PROJECT_FIELD_NUMBER = 2;
    private java.util.List<org.dodgybits.shuffle.dto.ShuffleProtos.Project> project_ =
      java.util.Collections.emptyList();
    public java.util.List<org.dodgybits.shuffle.dto.ShuffleProtos.Project> getProjectList() {
      return project_;
    }
    public int getProjectCount() { return project_.size(); }
    public org.dodgybits.shuffle.dto.ShuffleProtos.Project getProject(int index) {
      return project_.get(index);
    }
    
    // repeated .shuffle.Task task = 3;
    public static final int TASK_FIELD_NUMBER = 3;
    private java.util.List<org.dodgybits.shuffle.dto.ShuffleProtos.Task> task_ =
      java.util.Collections.emptyList();
    public java.util.List<org.dodgybits.shuffle.dto.ShuffleProtos.Task> getTaskList() {
      return task_;
    }
    public int getTaskCount() { return task_.size(); }
    public org.dodgybits.shuffle.dto.ShuffleProtos.Task getTask(int index) {
      return task_.get(index);
    }
    
    @Override
    public final boolean isInitialized() {
      for (org.dodgybits.shuffle.dto.ShuffleProtos.Context element : getContextList()) {
        if (!element.isInitialized()) return false;
      }
      for (org.dodgybits.shuffle.dto.ShuffleProtos.Project element : getProjectList()) {
        if (!element.isInitialized()) return false;
      }
      for (org.dodgybits.shuffle.dto.ShuffleProtos.Task element : getTaskList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (org.dodgybits.shuffle.dto.ShuffleProtos.Context element : getContextList()) {
        output.writeMessage(1, element);
      }
      for (org.dodgybits.shuffle.dto.ShuffleProtos.Project element : getProjectList()) {
        output.writeMessage(2, element);
      }
      for (org.dodgybits.shuffle.dto.ShuffleProtos.Task element : getTaskList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (org.dodgybits.shuffle.dto.ShuffleProtos.Context element : getContextList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      for (org.dodgybits.shuffle.dto.ShuffleProtos.Project element : getProjectList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      for (org.dodgybits.shuffle.dto.ShuffleProtos.Task element : getTaskList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue prototype) {
      return new Builder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue.newBuilder()
      private Builder() {}
      
      org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue result = new org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue();
      
      @Override
      protected org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue.getDescriptor();
      }
      
      public org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue getDefaultInstanceForType() {
        return org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue.getDefaultInstance();
      }
      
      public org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue build() {
        if (result != null && !isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");  }
        if (result.context_ != java.util.Collections.EMPTY_LIST) {
          result.context_ =
            java.util.Collections.unmodifiableList(result.context_);
        }
        if (result.project_ != java.util.Collections.EMPTY_LIST) {
          result.project_ =
            java.util.Collections.unmodifiableList(result.project_);
        }
        if (result.task_ != java.util.Collections.EMPTY_LIST) {
          result.task_ =
            java.util.Collections.unmodifiableList(result.task_);
        }
        org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue) {
          return mergeFrom((org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue other) {
        if (other == org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue.getDefaultInstance()) return this;
        if (!other.context_.isEmpty()) {
          if (result.context_.isEmpty()) {
            result.context_ = new java.util.ArrayList<org.dodgybits.shuffle.dto.ShuffleProtos.Context>();
          }
          result.context_.addAll(other.context_);
        }
        if (!other.project_.isEmpty()) {
          if (result.project_.isEmpty()) {
            result.project_ = new java.util.ArrayList<org.dodgybits.shuffle.dto.ShuffleProtos.Project>();
          }
          result.project_.addAll(other.project_);
        }
        if (!other.task_.isEmpty()) {
          if (result.task_.isEmpty()) {
            result.task_ = new java.util.ArrayList<org.dodgybits.shuffle.dto.ShuffleProtos.Task>();
          }
          result.task_.addAll(other.task_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              org.dodgybits.shuffle.dto.ShuffleProtos.Context.Builder subBuilder = org.dodgybits.shuffle.dto.ShuffleProtos.Context.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addContext(subBuilder.buildPartial());
              break;
            }
            case 18: {
              org.dodgybits.shuffle.dto.ShuffleProtos.Project.Builder subBuilder = org.dodgybits.shuffle.dto.ShuffleProtos.Project.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProject(subBuilder.buildPartial());
              break;
            }
            case 26: {
              org.dodgybits.shuffle.dto.ShuffleProtos.Task.Builder subBuilder = org.dodgybits.shuffle.dto.ShuffleProtos.Task.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTask(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .shuffle.Context context = 1;
      public java.util.List<org.dodgybits.shuffle.dto.ShuffleProtos.Context> getContextList() {
        return java.util.Collections.unmodifiableList(result.context_);
      }
      public int getContextCount() {
        return result.getContextCount();
      }
      public org.dodgybits.shuffle.dto.ShuffleProtos.Context getContext(int index) {
        return result.getContext(index);
      }
      public Builder setContext(int index, org.dodgybits.shuffle.dto.ShuffleProtos.Context value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.context_.set(index, value);
        return this;
      }
      public Builder setContext(int index, org.dodgybits.shuffle.dto.ShuffleProtos.Context.Builder builderForValue) {
        result.context_.set(index, builderForValue.build());
        return this;
      }
      public Builder addContext(org.dodgybits.shuffle.dto.ShuffleProtos.Context value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.context_.isEmpty()) {
          result.context_ = new java.util.ArrayList<org.dodgybits.shuffle.dto.ShuffleProtos.Context>();
        }
        result.context_.add(value);
        return this;
      }
      public Builder addContext(org.dodgybits.shuffle.dto.ShuffleProtos.Context.Builder builderForValue) {
        if (result.context_.isEmpty()) {
          result.context_ = new java.util.ArrayList<org.dodgybits.shuffle.dto.ShuffleProtos.Context>();
        }
        result.context_.add(builderForValue.build());
        return this;
      }
      public Builder addAllContext(
          java.lang.Iterable<? extends org.dodgybits.shuffle.dto.ShuffleProtos.Context> values) {
        if (result.context_.isEmpty()) {
          result.context_ = new java.util.ArrayList<org.dodgybits.shuffle.dto.ShuffleProtos.Context>();
        }
        super.addAll(values, result.context_);
        return this;
      }
      public Builder clearContext() {
        result.context_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .shuffle.Project project = 2;
      public java.util.List<org.dodgybits.shuffle.dto.ShuffleProtos.Project> getProjectList() {
        return java.util.Collections.unmodifiableList(result.project_);
      }
      public int getProjectCount() {
        return result.getProjectCount();
      }
      public org.dodgybits.shuffle.dto.ShuffleProtos.Project getProject(int index) {
        return result.getProject(index);
      }
      public Builder setProject(int index, org.dodgybits.shuffle.dto.ShuffleProtos.Project value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.project_.set(index, value);
        return this;
      }
      public Builder setProject(int index, org.dodgybits.shuffle.dto.ShuffleProtos.Project.Builder builderForValue) {
        result.project_.set(index, builderForValue.build());
        return this;
      }
      public Builder addProject(org.dodgybits.shuffle.dto.ShuffleProtos.Project value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.project_.isEmpty()) {
          result.project_ = new java.util.ArrayList<org.dodgybits.shuffle.dto.ShuffleProtos.Project>();
        }
        result.project_.add(value);
        return this;
      }
      public Builder addProject(org.dodgybits.shuffle.dto.ShuffleProtos.Project.Builder builderForValue) {
        if (result.project_.isEmpty()) {
          result.project_ = new java.util.ArrayList<org.dodgybits.shuffle.dto.ShuffleProtos.Project>();
        }
        result.project_.add(builderForValue.build());
        return this;
      }
      public Builder addAllProject(
          java.lang.Iterable<? extends org.dodgybits.shuffle.dto.ShuffleProtos.Project> values) {
        if (result.project_.isEmpty()) {
          result.project_ = new java.util.ArrayList<org.dodgybits.shuffle.dto.ShuffleProtos.Project>();
        }
        super.addAll(values, result.project_);
        return this;
      }
      public Builder clearProject() {
        result.project_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .shuffle.Task task = 3;
      public java.util.List<org.dodgybits.shuffle.dto.ShuffleProtos.Task> getTaskList() {
        return java.util.Collections.unmodifiableList(result.task_);
      }
      public int getTaskCount() {
        return result.getTaskCount();
      }
      public org.dodgybits.shuffle.dto.ShuffleProtos.Task getTask(int index) {
        return result.getTask(index);
      }
      public Builder setTask(int index, org.dodgybits.shuffle.dto.ShuffleProtos.Task value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.task_.set(index, value);
        return this;
      }
      public Builder setTask(int index, org.dodgybits.shuffle.dto.ShuffleProtos.Task.Builder builderForValue) {
        result.task_.set(index, builderForValue.build());
        return this;
      }
      public Builder addTask(org.dodgybits.shuffle.dto.ShuffleProtos.Task value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.task_.isEmpty()) {
          result.task_ = new java.util.ArrayList<org.dodgybits.shuffle.dto.ShuffleProtos.Task>();
        }
        result.task_.add(value);
        return this;
      }
      public Builder addTask(org.dodgybits.shuffle.dto.ShuffleProtos.Task.Builder builderForValue) {
        if (result.task_.isEmpty()) {
          result.task_ = new java.util.ArrayList<org.dodgybits.shuffle.dto.ShuffleProtos.Task>();
        }
        result.task_.add(builderForValue.build());
        return this;
      }
      public Builder addAllTask(
          java.lang.Iterable<? extends org.dodgybits.shuffle.dto.ShuffleProtos.Task> values) {
        if (result.task_.isEmpty()) {
          result.task_ = new java.util.ArrayList<org.dodgybits.shuffle.dto.ShuffleProtos.Task>();
        }
        super.addAll(values, result.task_);
        return this;
      }
      public Builder clearTask() {
        result.task_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      org.dodgybits.shuffle.dto.ShuffleProtos.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_shuffle_Context_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shuffle_Context_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_shuffle_Project_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shuffle_Project_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_shuffle_Task_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shuffle_Task_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_shuffle_Date_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shuffle_Date_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_shuffle_Catalogue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shuffle_Catalogue_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\rshuffle.proto\022\007shuffle\"F\n\007Context\022\n\n\002i" +
      "d\030\001 \002(\003\022\014\n\004name\030\002 \002(\t\022\023\n\013colourIndex\030\003 \001" +
      "(\005\022\014\n\004icon\030\004 \001(\t\"=\n\007Project\022\n\n\002id\030\001 \002(\003\022" +
      "\014\n\004name\030\002 \002(\t\022\030\n\020defaultContextId\030\003 \001(\003\"" +
      "\270\002\n\004Task\022\n\n\002id\030\001 \002(\003\022\023\n\013description\030\002 \002(" +
      "\t\022\017\n\007details\030\003 \001(\t\022\021\n\tcontextId\030\004 \001(\003\022\021\n" +
      "\tprojectId\030\005 \001(\003\022\036\n\007created\030\006 \001(\0132\r.shuf" +
      "fle.Date\022\037\n\010modified\030\007 \001(\0132\r.shuffle.Dat" +
      "e\022 \n\tstartDate\030\010 \001(\0132\r.shuffle.Date\022\036\n\007d" +
      "ueDate\030\t \001(\0132\r.shuffle.Date\022\020\n\010timezone\030" +
      "\n \001(\t\022\016\n\006allDay\030\013 \001(\010\022\022\n\ncalEventId\030\014 \001(" +
      "\003\022\r\n\005order\030\r \001(\005\022\020\n\010complete\030\016 \001(\010\"\026\n\004Da" +
      "te\022\016\n\006millis\030\001 \002(\003\"n\n\tCatalogue\022!\n\007conte" +
      "xt\030\001 \003(\0132\020.shuffle.Context\022!\n\007project\030\002 " +
      "\003(\0132\020.shuffle.Project\022\033\n\004task\030\003 \003(\0132\r.sh" +
      "uffle.TaskB*\n\031org.dodgybits.shuffle.dtoB" +
      "\rShuffleProtos";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_shuffle_Context_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_shuffle_Context_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_shuffle_Context_descriptor,
              new java.lang.String[] { "Id", "Name", "ColourIndex", "Icon", },
              org.dodgybits.shuffle.dto.ShuffleProtos.Context.class,
              org.dodgybits.shuffle.dto.ShuffleProtos.Context.Builder.class);
          internal_static_shuffle_Project_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_shuffle_Project_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_shuffle_Project_descriptor,
              new java.lang.String[] { "Id", "Name", "DefaultContextId", },
              org.dodgybits.shuffle.dto.ShuffleProtos.Project.class,
              org.dodgybits.shuffle.dto.ShuffleProtos.Project.Builder.class);
          internal_static_shuffle_Task_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_shuffle_Task_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_shuffle_Task_descriptor,
              new java.lang.String[] { "Id", "Description", "Details", "ContextId", "ProjectId", "Created", "Modified", "StartDate", "DueDate", "Timezone", "AllDay", "CalEventId", "Order", "Complete", },
              org.dodgybits.shuffle.dto.ShuffleProtos.Task.class,
              org.dodgybits.shuffle.dto.ShuffleProtos.Task.Builder.class);
          internal_static_shuffle_Date_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_shuffle_Date_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_shuffle_Date_descriptor,
              new java.lang.String[] { "Millis", },
              org.dodgybits.shuffle.dto.ShuffleProtos.Date.class,
              org.dodgybits.shuffle.dto.ShuffleProtos.Date.Builder.class);
          internal_static_shuffle_Catalogue_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_shuffle_Catalogue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_shuffle_Catalogue_descriptor,
              new java.lang.String[] { "Context", "Project", "Task", },
              org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue.class,
              org.dodgybits.shuffle.dto.ShuffleProtos.Catalogue.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
